"""
MCP Tools - Auto-generated importable wrappers for MCP servers.

This package is automatically generated by mcp-coordinator.
DO NOT EDIT MANUALLY.

Usage:
    from mcp_tools import list_servers
    from mcp_tools.chroma import query, add_documents
"""

def list_servers() -> list[str]:
    """Get list of all available MCP servers."""
    return ['docker-mcp', 'chroma', 'arxiv-mcp-server', 'wolframalpha', 'neo4j-mcp', 'advanced-reasoning', 'fmcp', 'graph-of-thoughts', 'reflective_agent_architecture', 'mcp-logic', 'AstAnalyzer', 'LocalREPL', 'mcp-server-qdrant-enhanced', 'mcp-creator', 'mcp-obsidian', 'memvid_mcp_server', 'mcts-mcp-server', 'openended-philosophy', 'fetch', 'project-synapse', 'cognitive-memory-engine', 'hybrid-ai', 'coinbase-trade-assistant', 'astermind-elm']
