"""
MCP Tools - Auto-generated importable wrappers for MCP servers.

This package is automatically generated by mcp-coordinator.
DO NOT EDIT MANUALLY.

Usage:
    from mcp_tools import list_servers
    from mcp_tools.desktop-commander import run_command
"""

def list_servers() -> list[str]:
    """Get list of all available MCP servers."""
    return []
